name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm  
        run: npm install -g pnpm  

      - name: 📦 Install Dependencies
        run: pnpm install  
        working-directory: ./src

      - name: 🌌 Build Pages
        run: pnpm run build
        working-directory: ./src

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES }}
          publish_dir: ./src/dist
          force_orphan: true
